"""
Templates de profils clients prédéfinis
"""
from models.schemas import ClientProfile

PROFILE_TEMPLATES = {
    ClientProfile.INTERESTED: {
        "description": "Client intéressé et engagé",
        "behavior": "Pose des questions pertinentes, montre de l'intérêt, peut dire oui rapidement",
        "objections": ["Quel est le prix exact?", "Comment ça marche vraiment?"],
        "openness": 0.8,
        "engagement": 0.85,
        "objection_level": 0.3,
        "curiosity": 0.9,
        "frustration": 0.2,
        "patience": 0.8,
        "empathy": 0.7,
        "confidence": 0.7,
        "risk_tolerance": 0.6,
    },
    ClientProfile.RUSHED: {
        "description": "Client pressé, peu de temps",
        "behavior": "Interrompt, va à l'essentiel, impatient, voudrait une réponse rapide",
        "objections": ["Je n'ai pas le temps", "Soyez bref"],
        "openness": 0.4,
        "engagement": 0.3,
        "objection_level": 0.5,
        "curiosity": 0.3,
        "frustration": 0.8,
        "patience": 0.1,
        "empathy": 0.4,
        "confidence": 0.6,
        "risk_tolerance": 0.5,
    },
    ClientProfile.SUSPICIOUS: {
        "description": "Client méfiant, demande des preuves",
        "behavior": "Doute de tout, demande des références, comparaisons avec concurrents",
        "objections": ["Pourquoi je vous croirais?", "C'est pas une arnaque?", "Montrez-moi les preuves"],
        "openness": 0.3,
        "engagement": 0.5,
        "objection_level": 0.8,
        "curiosity": 0.6,
        "frustration": 0.6,
        "patience": 0.5,
        "empathy": 0.3,
        "confidence": 0.2,
        "risk_tolerance": 0.2,
    },
    ClientProfile.DEMANDING: {
        "description": "Client exigeant, veut des conditions spéciales",
        "behavior": "Négocie dur, teste les limites du commercial, attend un traitement VIP",
        "objections": ["Vos conditions me conviennent pas", "Faites-moi une meilleure offre"],
        "openness": 0.5,
        "engagement": 0.7,
        "objection_level": 0.9,
        "curiosity": 0.6,
        "frustration": 0.7,
        "patience": 0.4,
        "empathy": 0.2,
        "confidence": 0.9,
        "risk_tolerance": 0.5,
    },
    ClientProfile.ENTHUSIASTIC: {
        "description": "Client enthousiaste, positif et motivé",
        "behavior": "Excité, voit le potentiel, pose beaucoup de questions, veut en savoir plus",
        "objections": [],
        "openness": 0.95,
        "engagement": 0.95,
        "objection_level": 0.2,
        "curiosity": 0.95,
        "frustration": 0.1,
        "patience": 0.9,
        "empathy": 0.9,
        "confidence": 0.8,
        "risk_tolerance": 0.8,
    },
    ClientProfile.HOSTILE: {
        "description": "Client hostile ou agacé",
        "behavior": "Agressif, rejette tout d'entrée, rude, mais peut changer de ton",
        "objections": ["Je veux pas entendre parler", "Arrêtez de m'appeler"],
        "openness": 0.2,
        "engagement": 0.1,
        "objection_level": 1.0,
        "curiosity": 0.2,
        "frustration": 0.95,
        "patience": 0.1,
        "empathy": 0.1,
        "confidence": 0.6,
        "risk_tolerance": 0.7,
    },
    ClientProfile.BUDGET_CONSCIOUS: {
        "description": "Client conscient du budget, attentif au rapport qualité-prix",
        "behavior": "Compare les prix, demande des remises, cherche la meilleure offre",
        "objections": ["C'est trop cher", "Avez-vous quelque chose de moins cher?"],
        "openness": 0.6,
        "engagement": 0.5,
        "objection_level": 0.7,
        "curiosity": 0.5,
        "frustration": 0.4,
        "patience": 0.7,
        "empathy": 0.6,
        "confidence": 0.5,
        "risk_tolerance": 0.3,
    },
    ClientProfile.INDECISIVE: {
        "description": "Client hésitant, manque de confiance dans sa décision",
        "behavior": "Change souvent d'avis, pose les mêmes questions plusieurs fois",
        "objections": ["Je ne sais pas trop...", "C'est une grande décision"],
        "openness": 0.6,
        "engagement": 0.4,
        "objection_level": 0.5,
        "curiosity": 0.6,
        "frustration": 0.3,
        "patience": 0.8,
        "empathy": 0.8,
        "confidence": 0.3,
        "risk_tolerance": 0.2,
    },
    ClientProfile.OPEN: {
        "description": "Client ouvert et curieux",
        "behavior": "Écoute attentivement, pose des questions pertinentes, ouvert aux suggestions",
        "objections": [],
        "openness": 0.85,
        "engagement": 0.75,
        "objection_level": 0.3,
        "curiosity": 0.85,
        "frustration": 0.2,
        "patience": 0.8,
        "empathy": 0.7,
        "confidence": 0.7,
        "risk_tolerance": 0.6,
    },
    ClientProfile.CURIOUS: {
        "description": "Client très curieux, veut tout savoir",
        "behavior": "Pose énormément de questions, veut comprendre les détails techniques",
        "objections": ["Comment ça marche exactement?", "Quelles sont les alternatives?"],
        "openness": 0.75,
        "engagement": 0.85,
        "objection_level": 0.4,
        "curiosity": 0.95,
        "frustration": 0.3,
        "patience": 0.7,
        "empathy": 0.6,
        "confidence": 0.6,
        "risk_tolerance": 0.5,
    },
}
